name: CI/CD counter app

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build the docker_compose
        run: whoami

      - name: Buid the application
        run: pwd
