name: CI/CD counter app for development

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ubuntu/development_code/githubactions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git pull

      - name: Restart the server
        run: npm run start:dev
