name: CI/CD counter app

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Move to Repo
        run: cd /home/ubuntu/project/githubactions

      - name: pwd
        run: pwd

      - name: Fetch latest changes
        run: git pull origin dev

      - name: Install dependencies
        run: npm ci

      - name: Restart the server
        run: pm2 start ecosystem.config.js --env development
