name: CI/CD counter app for development

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ubuntu/development_code/githubactions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: pwd
        run: pwd

      - name: Switch Branch
        run: git checkout dev

      - name: Fetch latest changes
        run: git pull origin dev

      - name: Install dependencies
        run: npm ci

      - name: Restart the server
        run: pm2 start ecosystem.config.js --env development
