name: CI/CD counter app

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Go to dir
        run: cd /home/ubuntu/project/githubactions

      - name: make pull
        run: git pull origin master

      - name: restart the server
        run: pm2 restart 0
