name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Run workflow based on environment
        if: ${{ contains(github.event.ref, 'master') }}
        uses: ./.github/workflows/production.yml

      - name: Run workflow based on environment
        if: ${{ contains(github.event.ref, 'dev') }}
        uses: ./.github/workflows/development.yml
