name: CI/CD counter app for development

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ubuntu/production_code/githubactions

    steps:
      - name: pwd
        run: pwd

      - name: Fetch latest changes
        run: git pull

      - name: Restart the server
        run: npm run start:prod
