name: CI/CD counter app for development

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ubuntu/production_code/githubactions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Switch Branch
        run: git checkout master

      - name: Fetch latest changes
        run: git pull origin master

      - name: Install dependencies
        run: npm ci

      - name: Restart the server
        run: pm2 start index.js --env NODE_ENV=production
