name: CI/CD counter app

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Move to Repo
        run: cd ~/project/githubactions/

      - name: Fetch latest changes
        run: git pull origin master

      - name: Install dependencies
        run: npm ci

      - name: Restart the server
        run: pm2 start ecosystem.config.js --env production
